### ISSUE TITLE
The app crashes - could it be camera?

### ISSUE THREAD

**Issue by amin-wan-kenobi** [moaazsidat/react-native-qrcode-scanner#107]
In my app, I use QR scanner which is embedded in a component. When I keep opening and closing the component (which has the QR scanner) after several attempts (sometimes up to 50 times somethings 12), the app crashes. 
### How can it be reproduced?

My phone is connected to the Xcode by cable so I can see all the logs. When it crashes, The error is in Libraries, RNCamera.xcodeproj, RN, RNCamera.m, _setupOrDisableMetadataOutput
and it shows the bold line below: 
- (void)_setupOrDisableMetadataOutput
{
    if ([self isReadingBarCodes] && (_metadataOutput == nil || ![self.session.outputs containsObject:_metadataOutput])) {
        AVCaptureMetadataOutput *metadataOutput = [[AVCaptureMetadataOutput alloc] init];
        if ([self.session canAddOutput:metadataOutput]) {
            [metadataOutput setMetadataObjectsDelegate:self queue:self.sessionQueue];
            **[self.session addOutput:metadataOutput];**
            self.metadataOutput = metadataOutput;
        }
    } else if (_metadataOutput != nil && ![self isReadingBarCodes]) {
        [self.session removeOutput:_metadataOutput];
        _metadataOutput = nil;
    }
}

### Build details?

ios version: 11.3.1
react-native version: 0.43.4
react-native-camera: 1.0.3
react-native-qrcode-scanner: 1.0.1

**Comment by lavawaters** [comment]
Hello, 
I am having the exact same issue.  I believe the camera is crashing after about 50 scans or 2 minutes.  The app doesn't close but it just locks like it expects the camera to send it data and the camera isn't showing up.  Xcode shows no error and everything appears fine.  I'm using AVFoundation to do my QR scanning.  Is this the same for you and have you found a workaround?

**Comment by mattruddy** [comment]
Same issue, have either of you found a work around for it?

**Comment by mattruddy** [comment]
Is there any way you could show a code sample for reference?

**Comment by mhamzawey** [comment]
I get that Android traceback 
```
Fatal Exception: java.lang.RuntimeException: startPreview failed
       at android.hardware.Camera.startPreview(Camera.java)
       at com.google.android.cameraview.Camera1.startCameraPreview(Camera1.java:194)
       at com.google.android.cameraview.Camera1.start(Camera1.java:144)
       at com.google.android.cameraview.CameraView.start(CameraView.java:285)
       at org.reactnative.camera.RNCameraView.onHostResume(RNCameraView.java:482)
       at com.facebook.react.bridge.ReactContext$1.run(ReactContext.java:150)
       at android.os.Handler.handleCallback(Handler.java:790)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6653)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:822)
```

Could it be the same issue? and how to solve

**Comment by sandyalta** [comment]
> I get that Android traceback
> 
> ```
> Fatal Exception: java.lang.RuntimeException: startPreview failed
>        at android.hardware.Camera.startPreview(Camera.java)
>        at com.google.android.cameraview.Camera1.startCameraPreview(Camera1.java:194)
>        at com.google.android.cameraview.Camera1.start(Camera1.java:144)
>        at com.google.android.cameraview.CameraView.start(CameraView.java:285)
>        at org.reactnative.camera.RNCameraView.onHostResume(RNCameraView.java:482)
>        at com.facebook.react.bridge.ReactContext$1.run(ReactContext.java:150)
>        at android.os.Handler.handleCallback(Handler.java:790)
>        at android.os.Handler.dispatchMessage(Handler.java:99)
>        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
>        at android.os.Looper.loop(Looper.java:164)
>        at android.app.ActivityThread.main(ActivityThread.java:6653)
>        at java.lang.reflect.Method.invoke(Method.java)
>        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
>        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:822)
> ```
> 
> Could it be the same issue? and how to solve

i have the same issue, any thought about it?
